### ISSUE TITLE
Unsubscribe a validator

### ISSUE THREAD

**Issue by BaryonNetwork** [forbole/gaia_bot_monitor#1]
Is there a command to unsubscribe notifications for a specific validator?

**Comment by BaryonNetwork** [comment]
Should I just be using /mute ?

**Comment by sherry13131** [comment]
You can use /mute for now

**Comment by sherry13131** [comment]
Added unsubscribe command on commit https://github.com/forbole/gaia_bot_monitor/commit/aac208727c1492286861de1800cce5b2f2632323.
